# Site settings
title: Grayscale
email: your-email@domain.com
url: https://sagesteppe.github.io/DataVizGallery
description: "Here are some data visualizations which showcase my style. I try to create novel figures which catch a viewers attention, convey information, and suggest future directions, without being distracting. A figure is not complete until everything which can be stripped from it is stripped from it."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
